name: forced_updates_demo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #state management
  flutter_bloc: ^8.1.3
  #code gen
  freezed_annotation: ^2.4.1
  # json serialization
  json_annotation: ^4.8.1
  #http calls
  dio: ^5.3.3
  #code gen for http calls
  retrofit: ^4.0.1
  retrofit_generator: ^7.0.8
  #DI
  get_it: ^7.6.4
  injectable: ^2.3.0
  injectable_generator: ^2.4.0
  dartz: ^0.10.1

  #updater
  native_updater: ^0.1.1

  #app info
  package_info_plus: ^4.1.0

  #firebase
  firebase_core: ^2.16.0

  #remote config
  firebase_remote_config: ^4.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.3
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true
